
# CICD Steps
# 1. Build the image using Docker
# 2. Tag and push the image to ECR
  # tag optional, only on main
# 3. Run Migration, on failure exit.
# 4. Update the ECS task definition(web + worker), if 3 succeeds

name: Deploy to ECR
on:
  release: 
    types: [published]

## Request access for this to be added to Github secrets
# To do: secrets go into github settings, rotate the secrets the first. 
env: 
  STAGING_ENV: true
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    concurrency: staging_environment
    steps:
    - name: Determine Deployment Environment
      id: environment-checks
      if: ${{ startsWith(github.event.release.tag, 'stag') }}
      run: |
        echo "STAGING_ENV=staging" >> $STAGING_ENV
    - name: Confirm that env was set
      id: env-checks
      run: |
        echo "=========="
        echo $STAGING_ENV
        echo  ${{ github.github_ref }}
        echo  ${{ github.github_sha }}
        echo "========== Release"
        echo  ${{ github.event.release.name }} 
        echo  ${{ github.event.release.tagName }} 
        echo  ${{ github.event.release.tag }} 
        echo "========== Release body"
        echo  ${{ github.event.release.body }} 
